In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [10]:
data = {
    "Area":[2600,3000,3200,3600,4000],
    "Price":[550000,565000,610000,680000,725000]
}
df = pd.DataFrame(data)

In [11]:
print(df)

   Area   Price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000


In [14]:
model= linear_model.LinearRegression()

model.fit(df[['Area']],df.Price)

LinearRegression()

In [15]:
model.coef_

array([135.78767123])

In [16]:
model.intercept_

180616.43835616432

In [19]:
model.predict([[5000]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [20]:
import pickle

In [23]:
with open("model_pickle","wb") as f:
    pickle.dump(model,f)

In [24]:
with open("model_pickle","rb") as f:
    mp = pickle.load(f)

In [25]:
mp.predict([[5000]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [27]:
import joblib

In [28]:
joblib.dump(model,"model_joblib")

['model_joblib']

In [32]:
mj = joblib.load("model_joblib")

In [33]:
mj.predict([[5000]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [ ]:
mj.co